version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: d3
    versions:
    - 6.6.0
    - 6.6.1
    - 6.6.2
  - dependency-name: "@symfony/webpack-encore"
    versions:
    - 1.0.2
    - 1.0.3
    - 1.0.4
    - 1.0.5
    - 1.1.0
    - 1.1.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - ">= 13.12.a, < 13.13"
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.8.0
    - 15.9.0
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
